In [ ]:
import torch
from scipy.interpolate import CubicSpline
from scipy.integrate import solve_ivp
import numpy as np
import sys


In [28]:
from torchcubicspline import(natural_cubic_spline_coeffs, 
                             NaturalCubicSpline)

t = torch.tensor([0,1,2,3.,4,5])
y = torch.tensor([0,0,0,0.,0,0]).reshape(-1,1)

coeffs = natural_cubic_spline_coeffs(t, y)

cs = NaturalCubicSpline(coeffs)
tt = torch.tensor([0,1,2,3,4,5,0,1])

print(tt.storage().size())
t = tt.expand(5,-1)
print(tt.storage().size())
yy = cs.evaluate(tt)
print(yy.storage().size())


8
8
8


In [ ]:
x = torch.tensor([1,2,3,4,5,6,7,8])
y = torch.tensor([1,2,3,4,5,6,7,8]).reshape(-1,1)

x = x.expand(8,-1)
y = y.expand(-1,8)
print(x.storage().size())
print(y.storage().size())
print((x+y).storage().size())


torch.Size([8, 8])
torch.Size([8, 8])
64


In [3]:
g = CubicSpline([0,1,2,3,4,5,6,7,8,9,10],[1,1,1,1,1,1,1,1,1,1,1])

f = lambda t,y: g(t)

print(solve_ivp(f,(0,10),[0],'RK45',np.linspace(0,10,21)))

  message: The solver successfully reached the end of the integration interval.
  success: True
   status: 0
        t: [ 0.000e+00  5.000e-01 ...  9.500e+00  1.000e+01]
        y: [[ 0.000e+00  5.000e-01 ...  9.500e+00  1.000e+01]]
      sol: None
 t_events: None
 y_events: None
     nfev: 38
     njev: 0
      nlu: 0


In [4]:
bounds = torch.tensor([(0,0),(200,0),(0,200),(200,200)])
source_locations = torch.tensor([[0,0],[30,30]])

bounds = bounds.repeat(1,source_locations.shape[0])
source_locations = source_locations.reshape(1,bounds.shape[0])
min_amp = 2
eps=1e-8
rshp = torch.abs(bounds-source_locations).reshape(-1,2)
rshp[:,0] = rshp[:,0]
rshp[:,1] = rshp[:,1]
distances = (rshp[:,0]**2 + rshp[:,1]**2)**.5
times = distances/min_amp
max = torch.max(times)

In [5]:
x = torch.tensor([[1],[2],[3]])
x.reshape(-1).repeat(3,2,1)

tensor([[[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]],

        [[1, 2, 3],
         [1, 2, 3]]])

In [6]:
torch.tile(x.reshape(-1,1,1),(1,5,10))
print(torch.linspace(0,10,6).repeat(3,2,1))

tensor([[[ 0.,  2.,  4.,  6.,  8., 10.],
         [ 0.,  2.,  4.,  6.,  8., 10.]],

        [[ 0.,  2.,  4.,  6.,  8., 10.],
         [ 0.,  2.,  4.,  6.,  8., 10.]],

        [[ 0.,  2.,  4.,  6.,  8., 10.],
         [ 0.,  2.,  4.,  6.,  8., 10.]]])


In [7]:
x.expand((3,2)).nelement()
x.expand((3,7))

tensor([[1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3]])

In [8]:
import sys
def memory(x):
    return sys.getsizeof(x)

torch.tensor([5,4,3,2])
print(memory(x))
print(memory(x.expand((3,2))))


88
88
